### PR TITLE
test that yield is given number of seconds

### PR DESCRIPTION
**Pull request by jjb**
Nothing currently covers this behavior

### CODE REVIEW

**Comment by ioquatix** [comment]
This looks good to me but I feel a little bit odd about using a string. But it also works pretty well… what do you think?

**Comment by jjb** [comment]
My goal was to do something "realistic" which does something with the value, to test that the return value is what the block returns and also that the block has access to the param.

If we don't use a string, what alternative do you have in mind? one of these?

```ruby
    assert_equal 5, Timeout.timeout(5){|s| s }
    assert_equal 6, Timeout.timeout(5){|s| s+1 }
```

**Comment by ioquatix** [comment]
I would say there are two tests:

- That the time is provided to the block as an argument.
- That the value of the block is returned.

The biggest issue I see with the string formatting is time precision, but as long as we use an integer, it would be okay? But I'm not sure we can guarantee the value of the timeout argument? In the future we might want a more precise measurement of time than just the numeric value.

**Comment by jjb** [comment]
ah, so you are saying that involving the string interpolation makes the test brittle, because one day the code might, say, run to_f on s, and then the string will be "5.0 seconds" and the test will erroneously break?

what do you think of one of these?

```ruby
    assert_equal 5, Timeout.timeout(5){|s| s }
    assert_equal 6, Timeout.timeout(5){|s| s+1 }
    assert_equal [5, :ok], Timeout.timeout(5){|s| [s, :ok] }
    x = rand(1...10); assert_equal x, Timeout.timeout(x){|s| s }
```

**Comment by ioquatix** [comment]
I think as long as we consider the issue, I'm fine with whatever you ultimately propose.

**Comment by jjb** [comment]
Okay, I went with the array

**Comment by jjb** [comment]
I don't know why CI isn't running...

**Pull request merged**
